### ISSUE TITLE
It's not work on chrome

### ISSUE THREAD

**Issue by op69qs** [jmlntw/google-search-sidebar#22] opened 2019-12-03 03:33 UTC
It's not work on chrome,Firefox is fine

<img width="845" alt="iShot     2019-12-03 11 25 01" src="https://user-images.githubusercontent.com/46735012/70018245-7e97c080-15c0-11ea-8a25-6afbcf224b8e.png">

**Comment by mnghsn** [comment] 2019-12-03 08:45
I can not reproduce the bug in the latest Chrome. Please provide more information like your browser version, userscript or userstyle manager, etc.

**Comment by op69qs** [comment] 2019-12-04 01:59
My mistake
chrome: 79.0.3945.56
Tampermonkey: 4.9

**Comment by mnghsn** [comment] 2019-12-04 09:55
Strangely, it works for me here.
Check if you're using other extensions/userscripts that may modify the page. Or maybe Google is just doing some A/B testings.

I'll keep this issue open and see if anyone else is experiencing this.

**Comment by op69qs** [comment] 2019-12-05 02:16
I already try disabled other extensions or userscripts and the problem still came out.....
when I sign out my account the userscripts worked...
probably the A/B test is on my account..

**Comment by willyer** [comment] 2019-12-08 11:03
You can close bookmark toolbar.

**Comment by actionless** [comment] 2020-01-02 18:54
I have a similar issue but only on the "Images" search tab

Could it be also A/B feature rollout or you also can reproduce it?

**Comment by Rupthya** [comment] 2020-02-22 09:48
**問題自 2020-03-15 左右消失，一切功能恢復正常；原因未明。**

相同問題，自行排除各種搭配後不果，故轉至這裏彙報問題；

症狀同 https://github.com/jmlntw/google-search-sidebar/issues/24 裏 Wcw5504 第二則回覆所回報相同；

**只要登入特定 Google 帳號問題則顯現**；已自行排除所有腳本/樣式/擴充問題

系統 Windows 10 17134.137 64BIT, 
曾測試已知有問題的 Chrome 版本：
80.0.3987.106
80.0.3987.116


預設網址欄搜索腳本無效之網址：
例：
https://www.google.com/search?q=test
https://www.google.com.hk/search?q=test

使用其他區域 Google 搜索的鏈接則有效
例：
https://www.google.com.tw/search?q=test
https://www.google.co.jp/search?q=test


望解決，感謝作者。


P.S. Google Search Region 偶爾會不顯示的情況基於上述問題下變爲完全不會生效。

**Comment by op69qs** [comment] 2020-07-13 01:45
same issue happed with my account when use Edge browser, try  other account is OK .
Microsoft Edge: 84.0.516.1

**Comment by op69qs** [comment] 2020-07-14 06:18
```
#hdtbMenus.hdtb-td-c {
    opacity: 0;
    top: 68px;
}
```
找到了，这是不显示的原因

**Comment by mnghsn** [comment] 2020-10-24 00:25
I believe that this issue has been fixed in the latest version.

**Closed as completed by mnghsn** 2020-10-24 00:25 UTC
Labels: bug, help wanted
